server:
  port: 8001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springssdb
    username: springssapp
    password: Password02117

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect