spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learnjpa
    username: postgres
    password: Password02117

  jpa:
   hibernate.ddl-auto: update
   show-sql: true
   properties:
     hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect