app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/spring
      username: application
      password: Password02117
      pool-size: 30      

server:
  error:
    include-binding-errors: always
    include-message: always


